//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleHomepage.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Cart
    {
        public int CartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal? ProductPrice { get; set; }
        public string ProductName { get; set; }
        public decimal? Total { get { return ProductPrice * Quantity; } set { Total = value; } }

        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
