//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleHomepage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int CommentID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ThisDateTime { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string FullName { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
